services:
  db:
    image: postgres:13.16-bullseye
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "postgres",
          "-U",
          "root"
        ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5438:5432"
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
